Add Install-standalone-lava-instance.md
Linaro/lkft-remote-lab pull request #1
Opened 2019-01-14 11:19 UTC by chase-qi

Signed-off-by: Chase Qi <chase.qi@linaro.org>

2019-01-14 11:23 UTC, chase-qi commented
@mwasilew Here is the step-by-step installation guide for a standalone LAVA instance. Adding generic devices qemu and lxc included.  Would you please take a look? Please let me know if anything wrong or missing.

2019-01-14 12:34 UTC, mwasilew requested changes
It might be a good idea to make the lines a bit shorter. But apart from that and a few typing mistakes it looks good.

2019-01-14 12:34 UTC, mwasilew commented on LAVA/Install-standalone-lava-instance.md
> +    Email address: chase.qi@linaro.org
maybe use john.doe@example.com

2019-01-14 12:34 UTC, mwasilew commented on LAVA/Install-standalone-lava-instance.md
> +    Open link http://localhost/, you should be able to sing in with the super user created in the previous step.
s/sing/sign/

2019-01-14 12:34 UTC, mwasilew commented on LAVA/Install-standalone-lava-instance.md
> +3. Add device `CONFIG` file(aka device dictionary).
space missing before opening bracket

2019-01-15 04:49 UTC, chase-qi commented
> It might be a good idea to make the lines a bit shorter. But apart from that and a few typing mistakes it looks good.

I have fixed your comments and shorten the content line length < 80 and code&&link line length <120.

Thanks,
Chase

2019-01-15 09:23 UTC, mwasilew commented
Looks good. However I don't have enough rights to merge this patch.

2019-01-15 09:50 UTC, chase-qi commented
I though you have the permissions as you pushed some commits before. You are admin now :)

2019-01-15 10:21 UTC, mwasilew approved these changes

2019-01-15 10:21 UTC, merged